[package]
name = "seal-sdk-rs"
version = "0.1.0"
edition = "2024"
authors = ["Quentin Diebold <pro@quentindiebold.com>"]
license-file = "LICENSE"
readme = "README.md"

[dependencies]
async-trait = "0.1"
anyhow = "1"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "d1fcb853196c3de7888ed8fad74f419b8c8fbe3b", features = ["aes"] }
serde = { version = "1", features = ["derive"] }
sui-sdk-types = { git = "https://github.com/MystenLabs/sui-rust-sdk.git", features = ["serde"], tag = "sui-sdk-types-0.3.1", package = "sui-sdk-types" }
base64 = "0.22.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
seal_crypto = { package = "crypto", git = "https://github.com/mystenlabs/seal", rev = "6755476d6f2eb4e7069f073228516a8eb7c7c1ea" }
thiserror = "1"
bcs = "0.1"
rand = "0.8.5"
serde_json = "1.0.149"
chrono = "0.4"
hex = "0.4"
log = "0.4"

reqwest = { version = "0.11", optional = true, default-features = false, features = ["json"] }
http = { version = "0.2", optional = true }
moka = { version = "0.12", features = ["future"], optional = true }
sui_types = { git = "https://github.com/MystenLabs/sui", tag = "mainnet-v1.68.1", package = "sui-types", optional = true }
sui_keys = { git = "https://github.com/MystenLabs/sui", tag = "mainnet-v1.68.1", package = "sui-keys", optional = true }
sui_sdk = { git = "https://github.com/MystenLabs/sui", tag = "mainnet-v1.68.1", package = "sui-sdk", optional = true }
shared_crypto = { git = "https://github.com/MystenLabs/sui", tag = "mainnet-v1.68.1", package = "shared-crypto", optional = true }

[dev-dependencies]
testcontainers = "=0.25.0"
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", tag = "mainnet-v1.68.1", package = "sui-json-rpc-types" }

[features]
default = ["client", "rustls-tls", "native-sui-sdk"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
client = ["reqwest", "http"]
moka-client = ["moka"]
native-sui-sdk = ["sui_sdk", "sui_types", "sui_keys", "shared_crypto"]
